#+title: cl-wnbrowser

This is CL-WNBROWSER, a webinterface for the OpenWordnet-PT dataset.
It is currently running at http://openwordnet-pt.org

See also the OpenWordnet-PT project:
https://github.com/own-pt/openWordnet-PT

* Dependencies

- SBCL
- https://quicklisp.org/
- https://github.com/own-pt/clesc.git
- https://github.com/own-pt/graph-algorithms.git

See the ASD file.
    
* License

See the file LICENSE for details.

* The ElasticSearch

  Using the ES from IBM Cloud...

* Install

  See the Dockerfile and CODE-ENGINE.md

* Load no cl-wnbrowser e inicializacao do servidor

#+begin_src lisp
  (ql:quickload :cl-wnbrowser)
  (cl-wnbrowser::start-server 8080)
#+end_src
  
If lisp files changed, you can try loading them again.  This may not
work, given the dependencies between the different files.  The safest
option is to simply reload the application.

If only templates changed, you can safely update the application by
switching to the =CL-WNBROWSER= package and executing the
=(SETUP-TEMPLATES)= method.

* Deploy

The Dockerfile is used to deploy the app in the IBM Cloud Code Engine.

1. Crie um projeto no Code Engine
2. Crie um Secret no Code Engine
   1. Adicione `ES_PASSWORD` como uma variável de ambiente e preencha seu valor;
   2. Adicione `ES_URL` como uma variável de ambiente e preencha seu valor;
   3. Adicione `ES_USER` com o usuário do ES;
   4. Adicione `GITHUB_CLIENT_ID` como uma variável de ambiente e preencha seu valor;
   5. Adicione `GITHUB_CLIENT_SECRET` como uma variável de ambiente e preencha seu valor;
   6. Adicione `OWNPT_BASE_URL` com seu valor
   7. Adicione `OWNPT_ACCOUNTS_ADMIN` com valores separados por colon
   8. Adicione `OWNPT_ACCOUNTS_VOTE` com valores separados por colon
3. Com o Secret criado, crie uma nova aplicação
4. Insira o endereço da sua imagem no formulário de criação.
5. Defina pelo menos uma instância ativa
6. Defina o secret criado no passo 2 como variaveis de ambiente
7. Verifique e defina que a porta exposta seja a 8080
8. Clique em criar
9. Em intantes sua instancia deve estar dísponível para ser acessada.
